version: "3.1"
services:
  copo-mongo:
    image: tonietuk/copo-mongo
    volumes:
      - copo-mongo-data:/data/db
    networks:
      - copo-backend-network
    deploy:
      placement:
        constraints: [node.hostname == copo-3]
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    secrets:
      - copo_mongo_initdb_root_password
      - copo_mongo_user_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: "copo_admin"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/copo_mongo_initdb_root_password"
      MONGO_USER: "copo_user"
      MONGO_USER_PASSWORD_FILE: "/run/secrets/copo_mongo_user_password"
      MONGO_DB: "copo_mongo"
  copo-postgres:
    image: postgres:9.4
    volumes:
      - copo-postgres-data:/var/lib/postgresql/data
    networks:
      - copo-backend-network
    deploy:
      placement:
        constraints: [node.hostname == copo-3]
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    secrets:
      - copo_postgres_user_password
    environment:
      POSTGRES_DB: "copo"
      POSTGRES_USER: "copo_user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/copo_postgres_user_password"
  copo-redis:
    image: redis:alpine
    networks:
      - copo-frontend-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == copo-3]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  copo-web:
    image: tonietuk/copo-web
    volumes:
      - copo-web-data:/copo/media
      - copo-static-data:/copo/static
    networks:
      - copo-frontend-network
      - copo-backend-network
    deploy:
      placement:
        constraints: [node.hostname == copo-1]
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    secrets:
      - copo_web_secret_key
      - copo_postgres_user_password
      - copo_mongo_user_password
      - copo_google_secret_key
      - copo_figshare_client_id_key
      - copo_figshare_client_secret_key
      - copo_figshare_consumer_secret_key
      - copo_facebook_secret_key
      - copo_twitter_secret_key
      - copo_orcid_secret_key
      - copo_webin_user
      - copo_webin_user_password
    environment:
      SECRET_KEY_FILE: "/run/secrets/copo_web_secret_key"
      MEDIA_PATH: "media/"
      DEBUG: "false"
      REDIS_HOST: "copo-redis"
      REDIS_PORT: "6379"
      ASPERA_PLUGIN_DIRECTORY: "aspera_linux_plugin"
      WEBIN_USER_FILE: "/run/secrets/copo_webin_user"
      WEBIN_USER_PASSWORD_FILE:  "/run/secrets/copo_webin_user_password"
      MONGO_USER: "copo_user"
      MONGO_USER_PASSWORD_FILE: "/run/secrets/copo_mongo_user_password"
      MONGO_DB: "copo_mongo"
      MONGO_HOST: "copo-mongo"
      MONGO_PORT: "27017"
      MONGO_MAX_POOL_SIZE: "100"
      POSTGRES_DB: "copo"
      POSTGRES_USER: "copo_user"
      POSTGRES_PORT: "5432"
      POSTGRES_SERVICE: "copo-postgres"
      POSTGRES_PASSWORD_FILE: "/run/secrets/copo_postgres_user_password"
      ORCID_SECRET_FILE: "/run/secrets/copo_orcid_secret_key"
      FIGSHARE_CONSUMER_SECRET_FILE: "/run/secrets/copo_figshare_consumer_secret_key"
      FIGSHARE_CLIENT_ID_FILE: "/run/secrets/copo_figshare_client_id_key"
      FIGSHARE_CLIENT_SECRET_FILE: "/run/secrets/copo_figshare_client_secret_key"
      GOOGLE_SECRET_FILE: "/run/secrets/copo_google_secret_key"
      TWITTER_SECRET_FILE: "/run/secrets/copo_twitter_secret_key"
      FACEBOOK_SECRET_FILE: "/run/secrets/copo_facebook_secret_key"
    command: bash -c "python manage.py makemigrations rest && python manage.py makemigrations chunked_upload && python manage.py makemigrations && python manage.py migrate && python /copo/social.py && /usr/local/bin/gunicorn web.wsgi:application -w 4 -t 1000 -b :8000"
  copo-nginx:
    image: tonietuk/copo-nginx
    volumes:
      - copo-static-data:/www/static
    ports:
      - "80:80"
      #- "80:443"
    networks:
      - copo-frontend-network
    deploy:
      placement:
        constraints: [node.hostname == copo-1]
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    secrets:
      - copo-project.crt
      - copo-project.key

networks:
  copo-frontend-network:
  copo-backend-network:

volumes:
  copo-web-data:
  copo-static-data:
  copo-mongo-data:
  copo-postgres-data:

secrets:
  copo_mongo_initdb_root_password:
    external: true
  copo_mongo_user_password:
    external: true
  copo_postgres_user_password:
    external: true
  copo_web_secret_key:
    external: true
  copo_orcid_secret_key:
    external: true
  copo_figshare_consumer_secret_key:
    external: true
  copo_figshare_client_id_key:
    external: true
  copo_figshare_client_secret_key:
    external: true
  copo_google_secret_key:
    external: true
  copo_twitter_secret_key:
    external: true
  copo_facebook_secret_key:
    external: true
  copo_webin_user:
    external: true
  copo_webin_user_password:
    external: true
  copo-project.crt:
    external: true
  copo-project.key:
    external: true
